name: Documentation
description: Report an issue or suggest improvements for documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Report missing, incorrect, or unclear documentation.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README
        - Technical Documentation
        - API Documentation
        - Contributing Guide
        - Security Policy
        - Setup Guide
        - Code Comments
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong with the current documentation?
      placeholder: Describe the issue with the documentation
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is this documentation located?
      placeholder: File name, section, line number, or URL
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: Provide your suggested changes or additions

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Add any other context here

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have read the existing documentation
          required: true
        - label: I am willing to submit a PR to fix this
          required: false
